// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ngaq.Local.Db;

#nullable disable

namespace Ngaq.Local.Migrations
{
    [DbContext(typeof(DbCtx))]
    [Migration("20250504144512_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ngaq.Core.Model.Po.Kv.Po_Kv", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("KDescr")
                        .HasColumnType("TEXT");

                    b.Property<long>("KI64")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KStr")
                        .HasColumnType("TEXT");

                    b.Property<long>("KType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubjectIdType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectId_Str")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SubjectId_UInt128")
                        .HasColumnType("BLOB");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VDescr")
                        .HasColumnType("TEXT");

                    b.Property<double>("VF64")
                        .HasColumnType("REAL");

                    b.Property<long>("VI64")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VStr")
                        .HasColumnType("TEXT");

                    b.Property<long>("VType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KI64");

                    b.HasIndex("KStr");

                    b.HasIndex("SubjectId_UInt128");

                    b.ToTable("Kv", (string)null);
                });

            modelBuilder.Entity("Ngaq.Core.Model.Po.Word.Po_Word", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordFormId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordFormId");

                    b.HasIndex("WordFormId", "Lang")
                        .IsUnique();

                    b.ToTable("Word", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
