// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Ngaq.Local.Db;
using Ngaq.Local.GeneratedInterceptors;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DbCtx), typeof(DbCtxModel))]
