// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Ngaq.Local.GeneratedInterceptors
{
    public partial class DbCtxModel
    {
        private DbCtxModel()
            : base(skipDetectChanges: false, modelId: new Guid("0cddfab1-d52b-4f95-b7c9-a096a625ef81"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var po_Kv = Po_KvEntityType.Create(this);
            var po_Word = Po_WordEntityType.Create(this);

            Po_KvEntityType.CreateAnnotations(po_Kv);
            Po_WordEntityType.CreateAnnotations(po_Word);

            AddAnnotation("ProductVersion", "9.0.0");
        }
    }
}
